# Generated by packaging/homebrew/render-cask.py. Update the release manifest.
cask "chatgpt-community" do
  arch arm: "aarch64", intel: "x86_64"
  os linux: "linux"

  version "26.917.62051,1"
  sha256 arm64_linux:  "0a6a22d24ada853abe612235a7016fe5874cc0131f0796d22f19dc444b4c0ac3",
         x86_64_linux: "2a557388ff5a76cf0dfd304ed222ed1a9679f69dbbea8bcfd412119b1a17a67d"

  url "https://persistent.oaistatic.com/codex-app-prod/linux/rpm/#{arch}/chatgpt-#{version.csv.first}-1.#{arch}.rpm"
  name "ChatGPT Community"
  desc "ChatGPT with community Linux features, applied locally"
  homepage "https://github.com/bruglet/chatgpt-desktop-linux"

  livecheck do
    skip "Versions require downstream patch validation on both Linux architectures"
  end

  depends_on formula: "cpio"
  depends_on formula: "curl"
  depends_on formula: "node@24"
  depends_on formula: "python@3.14"
  depends_on formula: "rpm2cpio"
  depends_on formula: "rust"
  depends_on linux: :any
  container type: :naked

  data_home = (ENV["HOMEBREW_XDG_DATA_HOME"] || ENV.fetch("XDG_DATA_HOME", nil)).to_s
  data_home = "#{Dir.home}/.local/share" unless data_home.start_with?("/")
  desktop_file = "#{data_home}/applications/codex-desktop.desktop"

  command_wrapper "codex-desktop",
                  executable: "#{staged_path}/prepared/app/start.sh",
                  env:        { "BAMF_DESKTOP_FILE_HINT" => desktop_file }
  artifact "prepared/integration/codex-desktop.desktop",
           target: desktop_file
  artifact "prepared/integration/codex-desktop.png",
           target: "#{data_home}/icons/codex-desktop.png"

  preflight_steps do
    write_file "release.json", <<~JSON
      {
        "schemaVersion": 1,
        "ready": true,
        "version": "26.917.62051",
        "revision": 1,
        "sourceInputSha256": "e5e55bfd18aff59c1fa26b931db97ac50fa9590d501b4ca891f3b96b1ed28026",
        "source": {
          "commit": "be583fc8ae6d89fb11c23960bdf3c5f3218bc043",
          "url": "https://github.com/bruglet/chatgpt-desktop-linux/archive/be583fc8ae6d89fb11c23960bdf3c5f3218bc043.tar.gz",
          "sha256": "aabfcbf5c89afa0d77b72553bba23eb9e8145c750555e8539dc477ab0d4cbe07"
        },
        "campaign": {
          "repository": "https://persistent.oaistatic.com/codex-app-prod/linux/deb",
          "version": "26.917.62051",
          "packages": {
            "amd64": {
              "architecture": "amd64",
              "version": "26.917.62051",
              "repositoryPath": "pool/main/c/chatgpt/chatgpt_26.917.62051_amd64.deb",
              "sha256": "75536e3f197c6db8881a634f8bb9b0515184a8eff7cec9be5f408d0f4ae6e696",
              "size": 420738082
            },
            "arm64": {
              "architecture": "arm64",
              "version": "26.917.62051",
              "repositoryPath": "pool/main/c/chatgpt/chatgpt_26.917.62051_arm64.deb",
              "sha256": "baf06daf4df10e8642e0d6bf0e7a47da5cb7e2ffe12f44427371d2f325f55924",
              "size": 399802982
            }
          },
          "releaseId": "5dbee440a3013f9dd4e89779e6136d227b8e25be3751847c6c1ee63bee7349f8"
        },
        "features": {
          "enabled": [
            "mcp-helper-reaper",
            "node-repl-reaper",
            "tray-usage",
            "pet-overlay"
          ]
        },
        "packages": {
          "amd64": {
            "url": "https://persistent.oaistatic.com/codex-app-prod/linux/rpm/x86_64/chatgpt-26.917.62051-1.x86_64.rpm",
            "sha256": "2a557388ff5a76cf0dfd304ed222ed1a9679f69dbbea8bcfd412119b1a17a67d"
          },
          "arm64": {
            "url": "https://persistent.oaistatic.com/codex-app-prod/linux/rpm/aarch64/chatgpt-26.917.62051-1.aarch64.rpm",
            "sha256": "0a6a22d24ada853abe612235a7016fe5874cc0131f0796d22f19dc444b4c0ac3"
          }
        }
      }
    JSON
    write_file "bootstrap.py", <<~PYTHON
      """Cask bootstrap: verify pinned source before running the RPM adapter."""
      import hashlib
      import json
      import os
      import shutil
      import stat
      from pathlib import Path
      import subprocess
      import sys
      import tarfile
      import tempfile

      stage = Path(__file__).resolve().parent
      prefix = Path(sys.argv[1])
      # Homebrew stores command wrappers as read-only files. During rollback it restores
      # the predecessor's stage, reruns this preflight, and then rewrites that wrapper.
      wrapper = stage / ".homebrew-command-wrappers/codex-desktop"
      if wrapper.is_symlink():
          raise ValueError("Command wrapper must not be a symlink")
      if wrapper.exists():
          if not wrapper.is_file():
              raise ValueError("Command wrapper must be a regular file")
          wrapper.chmod(wrapper.stat().st_mode | stat.S_IWUSR)
      release = json.loads((stage / "release.json").read_text())
      source = release["source"]
      archive = stage / "source.tar.gz"
      subprocess.run([str(prefix / "bin/curl"), "--fail", "--location", "--proto", "=https",
                      "--tlsv1.2", "--retry", "3", "--output", str(archive), source["url"]], check=True)
      with archive.open("rb") as stream:
          if hashlib.file_digest(stream, "sha256").hexdigest() != source["sha256"]:
              raise ValueError("Source archive SHA-256 mismatch")
      source_root = stage / "source"
      source_root.mkdir()
      with tarfile.open(archive) as bundle:
          bundle.extractall(source_root, filter="data")
      roots = list(source_root.iterdir())
      if len(roots) != 1 or not roots[0].is_dir():
          raise ValueError("Expected one source archive root")
      rpms = list(stage.glob("*.rpm"))
      if len(rpms) != 1:
          raise ValueError("Expected one staged RPM")
      env = dict(os.environ)
      env["PATH"] = os.pathsep.join([str(prefix / "opt/node@24/bin"), str(prefix / "opt/python@3.14/libexec/bin"),
                                    str(prefix / "bin"), "/usr/bin", "/bin"])
      # Use Homebrew's sandbox-approved cache, not the user's Cargo/npm directories.
      cache = Path(subprocess.check_output([str(prefix / "bin/brew"), "--cache"], text=True).strip())
      # Homebrew reruns the predecessor's preflight when reverting an upgrade.
      # Build in a fresh directory, keeping the prior payload until preparation succeeds.
      with tempfile.TemporaryDirectory(prefix=".homebrew-bootstrap-", dir=stage) as work:
          prepared = Path(work) / "prepared"
          subprocess.run(["/bin/bash", str(roots[0] / "packaging/homebrew/prepare.sh"), str(rpms[0]),
                          str(stage / "release.json"), str(prepared), str(prefix),
                          str(cache / "chatgpt-community")], env=env, check=True)
          previous = stage / "prepared"
          if previous.is_symlink():
              raise ValueError("Prepared output must not be a symlink")
          if previous.exists():
              previous.rename(Path(work) / "previous")
          try:
              prepared.rename(previous)
          except OSError:
              backup = Path(work) / "previous"
              if backup.exists():
                  backup.rename(previous)
              raise
      # The installed payload and reports suffice for launch and uninstall.
      shutil.rmtree(source_root)
      archive.unlink()
    PYTHON
    run "{{HOMEBREW_PREFIX}}/opt/python@3.14/bin/python3.14",
        args:           ["{{staged_path}}/bootstrap.py", "{{HOMEBREW_PREFIX}}"],
        chdir:          "{{staged_path}}",
        network_access: true
  end

  caveats <<~EOS
    Homebrew manages updates. Close ChatGPT before upgrading or reinstalling.
    Shared ChatGPT/Codex profiles are retained on uninstall.
    The Electron sandbox requires host support for unprivileged user namespaces.
  EOS
end
