#!/usr/bin/env python3
"""Render a self-contained cask. No install-time code comes from a moving tap."""

import json
from pathlib import Path
import sys


def ruby_heredoc(source):
    # Unquoted Ruby heredocs require escaping both backslashes and interpolation.
    return source.replace("\\", "\\\\").replace("#{", "\\#{")


def render(release):
    version = release.get("version", "26.901.51231")
    revision = release.get("revision", 0)
    packages = release.get("packages", {
        "amd64": {"sha256": "5769e86e439303e58b07d9cc51a1f03c6bf0a9f9b4fa8bcd2c4553da6e025c23"},
        "arm64": {"sha256": "b86d3070b7c9c4968798b866a0117bef4cebb9ab6bb6d84111582d5976a6faca"},
    })
    header = f'''# Generated by packaging/homebrew/render-cask.py. Update the release manifest.
cask "chatgpt-community" do
  arch arm: "aarch64", intel: "x86_64"
  os linux: "linux"

  version "{version},{revision}"
  sha256 arm64_linux:  "{packages['arm64']['sha256']}",
         x86_64_linux: "{packages['amd64']['sha256']}"

  url "https://persistent.oaistatic.com/codex-app-prod/linux/rpm/#{{arch}}/chatgpt-#{{version.csv.first}}-1.#{{arch}}.rpm"
  name "ChatGPT Community"
  desc "ChatGPT with community Linux features, applied locally"
  homepage "https://github.com/bruglet/chatgpt-desktop-linux"

  livecheck do
    skip "Versions require downstream patch validation on both Linux architectures"
  end

'''
    if not release.get("ready"):
        return header + '''  disable! date: "2026-09-09", because: "the first pinned source release awaits Homebrew validation"

  depends_on linux: :any

  stage_only true
end
'''
    bootstrap = ruby_heredoc(Path(__file__).with_name("bootstrap.py").read_text())
    manifest = ruby_heredoc(json.dumps(release, indent=2))
    steps = f'''  depends_on formula: "cpio"
  depends_on formula: "curl"
  depends_on formula: "node@24"
  depends_on formula: "python@3.14"
  depends_on formula: "rpm"
  depends_on formula: "rust"
  depends_on linux: :any
  container type: :naked

  data_home = (ENV["HOMEBREW_XDG_DATA_HOME"] || ENV["XDG_DATA_HOME"]).to_s
  data_home = "#{{Dir.home}}/.local/share" unless data_home.start_with?("/")
  desktop_file = "#{{data_home}}/applications/codex-desktop.desktop"

  command_wrapper "codex-desktop",
                  executable: "#{{staged_path}}/prepared/app/start.sh",
                  env:        {{ "BAMF_DESKTOP_FILE_HINT" => desktop_file }}
  artifact "prepared/integration/codex-desktop.desktop",
           target: desktop_file
  artifact "prepared/integration/codex-desktop.png",
           target: "#{{data_home}}/icons/codex-desktop.png"

  preflight_steps do
    write_file "release.json", <<~JSON
{''.join(('      ' + line if line else '') + chr(10) for line in manifest.splitlines())}    JSON
    write_file "bootstrap.py", <<~PYTHON
{''.join(('      ' + line if line else '') + chr(10) for line in bootstrap.splitlines())}    PYTHON
    run "{{{{HOMEBREW_PREFIX}}}}/opt/python@3.14/bin/python3.14",
        args:           ["{{{{staged_path}}}}/bootstrap.py", "{{{{HOMEBREW_PREFIX}}}}"],
        chdir:          "{{{{staged_path}}}}",
        network_access: true
  end

  caveats <<~EOS
    Homebrew manages updates. Close ChatGPT before upgrading or reinstalling.
    Shared ChatGPT/Codex profiles are retained on uninstall.
    The Electron sandbox requires host support for unprivileged user namespaces.
  EOS
end
'''
    return header + steps


if __name__ == "__main__":
    manifest, output = map(Path, sys.argv[1:])
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render(json.loads(manifest.read_text())))
